name: app_hdd_monitor 
description: Aplicación de monitoreo de relés de paneles de incendios 
version: 1.0.0+1 

environment: 
  sdk: ">=2.17.0 <3.0.0" 

dependencies: 
  flutter: 
    sdk: flutter 
  firebase_core: ^2.30.0 
  firebase_auth: ^4.19.2 
  cloud_firestore: ^4.17.0 
  mqtt_client: ^10.2.1 
  go_router: ^13.2.4 

dev_dependencies: 
  flutter_test: 
    sdk: flutter 
  mockito: ^5.4.4 

flutter:
  uses-material-design: true