name: flut_hdd_monitor
description: "Una nueva solución de monitoreo general de paneles contra incendios"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.3
  provider: ^6.1.2
  collection: ^1.18.0
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^14.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "E:\\PQSolutions\\HDD-Monitor\\HDD-Monitor-GitHub\\APP\\flut_hdd_monitor\\lib\\models\\Activity_Monitor_26229.png"

flutter:
  uses-material-design: true
